# 最小歐幾里德距離：Matrix Operation
1. 生成兩個矩陣 各為n*n個隨機變數
2. 算出兩點間距離：進行x1-y1 以此類推相減 並取平成相加再開根號
3. 找出最近的兩個點

In [1]:
import numpy as np
np.set_printoptions(suppress=True) # 取消科學記號顯示方法

In [ ]:
# 清除變數
import gc #（garbage collector）
del x, y, d, c1, A, B, C
gc.collect()

### 生成兩隨機變數矩陣

In [2]:
x = np.random.uniform(0, 100, size=(4, 4)).round(1)
print(x)

y = np.random.uniform(0, 100, size=(4, 4)).round(1)
print(y)

[[ 1.9 23.4 22.4 56.3]
 [48.   3.2 96.6 44.5]
 [63.8 98.  20.9  7.3]
 [90.9 34.1 48.1 62.4]]
[[22.1 35.4 59.  94.7]
 [28.5 59.9 97.8 16.8]
 [84.  13.6 63.9 51. ]
 [18.8 24.  53.1 27.7]]


In [3]:
# 產出空array
d = []

# 產出x, y的各種組合
for i in range(len(x)):
    for j in range(len(y)):
        d.append((x[i], y[j]))

d = np.reshape(d, (16,8))
d

array([[ 1.9, 23.4, 22.4, 56.3, 22.1, 35.4, 59. , 94.7],
       [ 1.9, 23.4, 22.4, 56.3, 28.5, 59.9, 97.8, 16.8],
       [ 1.9, 23.4, 22.4, 56.3, 84. , 13.6, 63.9, 51. ],
       [ 1.9, 23.4, 22.4, 56.3, 18.8, 24. , 53.1, 27.7],
       [48. ,  3.2, 96.6, 44.5, 22.1, 35.4, 59. , 94.7],
       [48. ,  3.2, 96.6, 44.5, 28.5, 59.9, 97.8, 16.8],
       [48. ,  3.2, 96.6, 44.5, 84. , 13.6, 63.9, 51. ],
       [48. ,  3.2, 96.6, 44.5, 18.8, 24. , 53.1, 27.7],
       [63.8, 98. , 20.9,  7.3, 22.1, 35.4, 59. , 94.7],
       [63.8, 98. , 20.9,  7.3, 28.5, 59.9, 97.8, 16.8],
       [63.8, 98. , 20.9,  7.3, 84. , 13.6, 63.9, 51. ],
       [63.8, 98. , 20.9,  7.3, 18.8, 24. , 53.1, 27.7],
       [90.9, 34.1, 48.1, 62.4, 22.1, 35.4, 59. , 94.7],
       [90.9, 34.1, 48.1, 62.4, 28.5, 59.9, 97.8, 16.8],
       [90.9, 34.1, 48.1, 62.4, 84. , 13.6, 63.9, 51. ],
       [90.9, 34.1, 48.1, 62.4, 18.8, 24. , 53.1, 27.7]])

In [4]:
d.shape

# 產出空array
c1 = []

# 
n = 4

# 產出 xi-yi的矩陣
for i in range(len(x)):
    c_i = []
    c_i = d[:, i] - d[:, i + n]
    #c1.extend(c_i)
    c1.append(c_i)
    if i == 4:
        break
    print(c1)

[array([-20.2, -26.6, -82.1, -16.9,  25.9,  19.5, -36. ,  29.2,  41.7,
        35.3, -20.2,  45. ,  68.8,  62.4,   6.9,  72.1])]
[array([-20.2, -26.6, -82.1, -16.9,  25.9,  19.5, -36. ,  29.2,  41.7,
        35.3, -20.2,  45. ,  68.8,  62.4,   6.9,  72.1]), array([-12. , -36.5,   9.8,  -0.6, -32.2, -56.7, -10.4, -20.8,  62.6,
        38.1,  84.4,  74. ,  -1.3, -25.8,  20.5,  10.1])]
[array([-20.2, -26.6, -82.1, -16.9,  25.9,  19.5, -36. ,  29.2,  41.7,
        35.3, -20.2,  45. ,  68.8,  62.4,   6.9,  72.1]), array([-12. , -36.5,   9.8,  -0.6, -32.2, -56.7, -10.4, -20.8,  62.6,
        38.1,  84.4,  74. ,  -1.3, -25.8,  20.5,  10.1]), array([-36.6, -75.4, -41.5, -30.7,  37.6,  -1.2,  32.7,  43.5, -38.1,
       -76.9, -43. , -32.2, -10.9, -49.7, -15.8,  -5. ])]
[array([-20.2, -26.6, -82.1, -16.9,  25.9,  19.5, -36. ,  29.2,  41.7,
        35.3, -20.2,  45. ,  68.8,  62.4,   6.9,  72.1]), array([-12. , -36.5,   9.8,  -0.6, -32.2, -56.7, -10.4, -20.8,  62.6,
        38.1,  84.4,  74. ,  -

In [5]:
# 轉list為matrix
c1 = np.matrix(c1)
type(c1)

# 對c1重新塑形再轉置
c1 = c1.reshape((4,16))
c1 = c1.transpose(); 
print(c1)

[[-20.2 -12.  -36.6 -38.4]
 [-26.6 -36.5 -75.4  39.5]
 [-82.1   9.8 -41.5   5.3]
 [-16.9  -0.6 -30.7  28.6]
 [ 25.9 -32.2  37.6 -50.2]
 [ 19.5 -56.7  -1.2  27.7]
 [-36.  -10.4  32.7  -6.5]
 [ 29.2 -20.8  43.5  16.8]
 [ 41.7  62.6 -38.1 -87.4]
 [ 35.3  38.1 -76.9  -9.5]
 [-20.2  84.4 -43.  -43.7]
 [ 45.   74.  -32.2 -20.4]
 [ 68.8  -1.3 -10.9 -32.3]
 [ 62.4 -25.8 -49.7  45.6]
 [  6.9  20.5 -15.8  11.4]
 [ 72.1  10.1  -5.   34.7]]


In [7]:
# matrix計算
c2 = np.power(c1, 2).sum(axis=1) 
print(c2)
c3 = np.sqrt(c2).round(2)
print(c3)

[[ 3366.16]
 [ 9285.22]
 [ 8586.79]
 [ 2046.42]
 [ 5641.45]
 [ 4363.87]
 [ 2515.7 ]
 [ 3459.77]
 [14748.02]
 [ 8701.56]
 [11290.09]
 [ 8954.  ]
 [ 5897.23]
 [ 9108.85]
 [  847.46]
 [ 6529.51]]
[[ 58.02]
 [ 96.36]
 [ 92.66]
 [ 45.24]
 [ 75.11]
 [ 66.06]
 [ 50.16]
 [ 58.82]
 [121.44]
 [ 93.28]
 [106.25]
 [ 94.63]
 [ 76.79]
 [ 95.44]
 [ 29.11]
 [ 80.81]]


In [8]:
min = c3.min()
def finditem(element, matrix):
    result = []
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if matrix[i][j] == element:
                result.append((i, j))
    return result
finditem(min, c3)

[(14, 0)]

In [18]:
# 產出group矩陣並合併到c
group = []
for i in range(len(x)):
    for j in range(len(y)):
        di_group = ('x' + str(i) + 'y' + str(j))
        #print(di_group)
        group += [di_group]
    #print(di_group)
print(group)


print(len(group))
group = np.matrix(group).reshape((1,16))
group = group.transpose()

['x0y0', 'x0y1', 'x0y2', 'x0y3', 'x1y0', 'x1y1', 'x1y2', 'x1y3', 'x2y0', 'x2y1', 'x2y2', 'x2y3', 'x3y0', 'x3y1', 'x3y2', 'x3y3']
16


In [46]:
c4 = np.hstack((c3, group)) ; c4

matrix([['58.02', 'x0y0'],
        ['96.36', 'x0y1'],
        ['92.66', 'x0y2'],
        ['45.24', 'x0y3'],
        ['75.11', 'x1y0'],
        ['66.06', 'x1y1'],
        ['50.16', 'x1y2'],
        ['58.82', 'x1y3'],
        ['121.44', 'x2y0'],
        ['93.28', 'x2y1'],
        ['106.25', 'x2y2'],
        ['94.63', 'x2y3'],
        ['76.79', 'x3y0'],
        ['95.44', 'x3y1'],
        ['29.11', 'x3y2'],
        ['80.81', 'x3y3']], dtype='<U32')

In [79]:
# 測試會出現什麼組合
def list( matrix):
    result = []
    for i in range(len(matrix)):
#        for j in range(len(matrix[i])):
                result.append((matrix[i]))
    return result
list(c4)

[matrix([['58.02', 'x0y0']], dtype='<U32'),
 matrix([['96.36', 'x0y1']], dtype='<U32'),
 matrix([['92.66', 'x0y2']], dtype='<U32'),
 matrix([['45.24', 'x0y3']], dtype='<U32'),
 matrix([['75.11', 'x1y0']], dtype='<U32'),
 matrix([['66.06', 'x1y1']], dtype='<U32'),
 matrix([['50.16', 'x1y2']], dtype='<U32'),
 matrix([['58.82', 'x1y3']], dtype='<U32'),
 matrix([['121.44', 'x2y0']], dtype='<U32'),
 matrix([['93.28', 'x2y1']], dtype='<U32'),
 matrix([['106.25', 'x2y2']], dtype='<U32'),
 matrix([['94.63', 'x2y3']], dtype='<U32'),
 matrix([['76.79', 'x3y0']], dtype='<U32'),
 matrix([['95.44', 'x3y1']], dtype='<U32'),
 matrix([['29.11', 'x3y2']], dtype='<U32'),
 matrix([['80.81', 'x3y3']], dtype='<U32')]

In [76]:
# 測試：找出min
#a = c4[:, 0]
#a = np.matrix(a).astype(np.float)
#result = []
#for i in range(len(a)):
#    min = np.min(a)
#    if a[i] == min:
#        result.append((min))


In [70]:
a =c4[:, 0]
a = np.matrix(a).astype(np.float)
print(np.min(a))

[[ 58.02]
 [ 96.36]
 [ 92.66]
 [ 45.24]
 [ 75.11]
 [ 66.06]
 [ 50.16]
 [ 58.82]
 [121.44]
 [ 93.28]
 [106.25]
 [ 94.63]
 [ 76.79]
 [ 95.44]
 [ 29.11]
 [ 80.81]]


In [80]:
# 先轉matrix element為float
# 再找出組合
def min_group(matrix):
    temp = matrix[:, 0]
    temp = np.matrix(temp).astype(np.float)
    result = []
    for i in range(len(temp)):
        min = np.min(temp)
        if temp[i] == min:
            result.append((matrix[i]))
    return result

In [81]:
min_group(c4)

[matrix([['29.11', 'x3y2']], dtype='<U32')]